package ast

// Stmt is the interface all statements implement.
type Stmt interface {
	stmt()
}

// Equals is the EQUALS command, which assigns the value generated by Right
// to the variable, register, or dereferenced pointer in Left. The values
// must be of the same type.
type Equals struct {
	Left, Right Expr
}

// Print outputs a bit to the standard output. The bit is written in uppercase
// ASCII letters and is followed by a line feed.
type Print struct {
	Val Bit
}

// Read reads the next bit from the standard input. The bit is written in
// uppercase ASCII letters and may contain whitespace but no other characters.
type Read struct {
}

func (*Equals) stmt() {}
func (*Print) stmt()  {}
func (*Read) stmt()   {}
