// Code generated by goyacc -o syntax.go syntax.y. DO NOT EDIT.

//line syntax.y:2
package parser

import __yyfmt__ "fmt"

//line syntax.y:2

import "github.com/BenLubar/bit/ast"

//line syntax.y:7
type yySymType struct {
	yys  int
	line *ast.Line
	stmt ast.Stmt
	expr ast.Expr
	bit2 [2]ast.Bits
	bits ast.Bits
	bit  ast.Bit
}

const tNand = 57346
const tZero = 57347
const tOne = 57348
const tLineNumber = 57349
const tCode = 57350
const tOpen = 57351
const tClose = 57352
const tParenthesis = 57353
const tThe = 57354
const tValue = 57355
const tAt = 57356
const tBeyond = 57357
const tAddressOf = 57358
const tJumpRegister = 57359
const tVariable = 57360
const tGoto = 57361
const tIf = 57362
const tIs = 57363
const tEquals = 57364
const tPrint = 57365
const tRead = 57366

var yyToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"tNand",
	"tZero",
	"tOne",
	"tLineNumber",
	"tCode",
	"tOpen",
	"tClose",
	"tParenthesis",
	"tThe",
	"tValue",
	"tAt",
	"tBeyond",
	"tAddressOf",
	"tJumpRegister",
	"tVariable",
	"tGoto",
	"tIf",
	"tIs",
	"tEquals",
	"tPrint",
	"tRead",
}
var yyStatenames = [...]string{}

const yyEofCode = 1
const yyErrCode = 2
const yyInitialStackSize = 16

//line yacctab:1
var yyExca = [...]int{
	-1, 1,
	1, -1,
	-2, 0,
}

const yyPrivate = 57344

const yyLast = 83

var yyAct = [...]int{

	19, 15, 7, 8, 6, 5, 10, 23, 14, 58,
	7, 8, 57, 44, 22, 48, 38, 52, 47, 6,
	7, 8, 6, 21, 29, 51, 56, 30, 55, 36,
	10, 10, 31, 32, 33, 37, 39, 40, 26, 7,
	8, 27, 28, 16, 43, 54, 17, 53, 6, 6,
	10, 10, 18, 49, 50, 7, 8, 13, 12, 16,
	34, 35, 17, 41, 42, 25, 7, 8, 18, 9,
	7, 8, 45, 46, 60, 3, 59, 24, 2, 20,
	4, 11, 1,
}
var yyPact = [...]int{

	68, 68, -1000, 65, -1000, 61, -1000, -1000, -1000, 34,
	-1000, 4, -1000, 65, -15, 73, 54, 25, 65, -1000,
	-1000, 65, -1000, 50, 50, 50, 46, 50, -1000, 65,
	15, -1000, -1000, 6, 50, 50, -1000, 51, 53, -1000,
	-1000, 27, -1000, -8, 67, -1, -4, 65, 65, 5,
	-3, 35, 33, 11, 9, -9, -12, 70, 69, -1000,
	-1000,
}
var yyPgo = [...]int{

	0, 82, 78, 81, 8, 1, 79, 5, 0,
}
var yyR1 = [...]int{

	0, 1, 1, 2, 3, 3, 3, 4, 4, 5,
	5, 5, 5, 5, 5, 5, 6, 6, 6, 6,
	6, 6, 7, 7, 8, 8,
}
var yyR2 = [...]int{

	0, 1, 2, 5, 1, 2, 3, 3, 1, 5,
	4, 4, 3, 2, 2, 1, 0, 2, 7, 7,
	14, 14, 1, 2, 1, 1,
}
var yyChk = [...]int{

	-1000, -1, -2, 7, -2, -7, -8, 5, 6, 8,
	-8, -3, 24, 23, -4, -5, 9, 12, 18, -8,
	-6, 19, -8, 22, 4, 11, 13, 16, 17, -7,
	-7, -4, -4, -4, 14, 15, -5, 20, 10, -5,
	-5, 12, 11, 17, 21, 5, 6, 19, 19, -7,
	-7, 20, 20, 12, 12, 17, 17, 21, 21, 6,
	5,
}
var yyDef = [...]int{

	0, -2, 1, 0, 2, 0, 22, 24, 25, 0,
	23, 16, 4, 0, 0, 8, 0, 0, 0, 15,
	3, 0, 5, 0, 0, 0, 0, 0, 13, 14,
	17, 6, 7, 0, 0, 0, 12, 0, 0, 10,
	11, 0, 9, 0, 0, 18, 19, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 20,
	21,
}
var yyTok1 = [...]int{

	1,
}
var yyTok2 = [...]int{

	2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
	12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
	22, 23, 24,
}
var yyTok3 = [...]int{
	0,
}

var yyErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

//line yaccpar:1

/*	parser for yacc output	*/

var (
	yyDebug        = 0
	yyErrorVerbose = false
)

type yyLexer interface {
	Lex(lval *yySymType) int
	Error(s string)
}

type yyParser interface {
	Parse(yyLexer) int
	Lookahead() int
}

type yyParserImpl struct {
	lval  yySymType
	stack [yyInitialStackSize]yySymType
	char  int
}

func (p *yyParserImpl) Lookahead() int {
	return p.char
}

func yyNewParser() yyParser {
	return &yyParserImpl{}
}

const yyFlag = -1000

func yyTokname(c int) string {
	if c >= 1 && c-1 < len(yyToknames) {
		if yyToknames[c-1] != "" {
			return yyToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func yyStatname(s int) string {
	if s >= 0 && s < len(yyStatenames) {
		if yyStatenames[s] != "" {
			return yyStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func yyErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !yyErrorVerbose {
		return "syntax error"
	}

	for _, e := range yyErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + yyTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := yyPact[state]
	for tok := TOKSTART; tok-1 < len(yyToknames); tok++ {
		if n := base + tok; n >= 0 && n < yyLast && yyChk[yyAct[n]] == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if yyDef[state] == -2 {
		i := 0
		for yyExca[i] != -1 || yyExca[i+1] != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; yyExca[i] >= 0; i += 2 {
			tok := yyExca[i]
			if tok < TOKSTART || yyExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if yyExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += yyTokname(tok)
	}
	return res
}

func yylex1(lex yyLexer, lval *yySymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = yyTok1[0]
		goto out
	}
	if char < len(yyTok1) {
		token = yyTok1[char]
		goto out
	}
	if char >= yyPrivate {
		if char < yyPrivate+len(yyTok2) {
			token = yyTok2[char-yyPrivate]
			goto out
		}
	}
	for i := 0; i < len(yyTok3); i += 2 {
		token = yyTok3[i+0]
		if token == char {
			token = yyTok3[i+1]
			goto out
		}
	}

out:
	if token == 0 {
		token = yyTok2[1] /* unknown char */
	}
	if yyDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", yyTokname(token), uint(char))
	}
	return char, token
}

func yyParse(yylex yyLexer) int {
	return yyNewParser().Parse(yylex)
}

func (yyrcvr *yyParserImpl) Parse(yylex yyLexer) int {
	var yyn int
	var yyVAL yySymType
	var yyDollar []yySymType
	_ = yyDollar // silence set and not used
	yyS := yyrcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	yystate := 0
	yyrcvr.char = -1
	yytoken := -1 // yyrcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		yystate = -1
		yyrcvr.char = -1
		yytoken = -1
	}()
	yyp := -1
	goto yystack

ret0:
	return 0

ret1:
	return 1

yystack:
	/* put a state and value onto the stack */
	if yyDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", yyTokname(yytoken), yyStatname(yystate))
	}

	yyp++
	if yyp >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyS[yyp] = yyVAL
	yyS[yyp].yys = yystate

yynewstate:
	yyn = yyPact[yystate]
	if yyn <= yyFlag {
		goto yydefault /* simple state */
	}
	if yyrcvr.char < 0 {
		yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
	}
	yyn += yytoken
	if yyn < 0 || yyn >= yyLast {
		goto yydefault
	}
	yyn = yyAct[yyn]
	if yyChk[yyn] == yytoken { /* valid shift */
		yyrcvr.char = -1
		yytoken = -1
		yyVAL = yyrcvr.lval
		yystate = yyn
		if Errflag > 0 {
			Errflag--
		}
		goto yystack
	}

yydefault:
	/* default state action */
	yyn = yyDef[yystate]
	if yyn == -2 {
		if yyrcvr.char < 0 {
			yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if yyExca[xi+0] == -1 && yyExca[xi+1] == yystate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			yyn = yyExca[xi+0]
			if yyn < 0 || yyn == yytoken {
				break
			}
		}
		yyn = yyExca[xi+1]
		if yyn < 0 {
			goto ret0
		}
	}
	if yyn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			yylex.Error(yyErrorMessage(yystate, yytoken))
			Nerrs++
			if yyDebug >= 1 {
				__yyfmt__.Printf("%s", yyStatname(yystate))
				__yyfmt__.Printf(" saw %s\n", yyTokname(yytoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for yyp >= 0 {
				yyn = yyPact[yyS[yyp].yys] + yyErrCode
				if yyn >= 0 && yyn < yyLast {
					yystate = yyAct[yyn] /* simulate a shift of "error" */
					if yyChk[yystate] == yyErrCode {
						goto yystack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if yyDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", yyS[yyp].yys)
				}
				yyp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", yyTokname(yytoken))
			}
			if yytoken == yyEofCode {
				goto ret1
			}
			yyrcvr.char = -1
			yytoken = -1
			goto yynewstate /* try again in the same state */
		}
	}

	/* reduction by production yyn */
	if yyDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", yyn, yyStatname(yystate))
	}

	yynt := yyn
	yypt := yyp
	_ = yypt // guard against "declared and not used"

	yyp -= yyR2[yyn]
	// yyp is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if yyp+1 >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyVAL = yyS[yyp+1]

	/* consult goto table to find next state */
	yyn = yyR1[yyn]
	yyg := yyPgo[yyn]
	yyj := yyg + yyS[yyp].yys + 1

	if yyj >= yyLast {
		yystate = yyAct[yyg]
	} else {
		yystate = yyAct[yyj]
		if yyChk[yystate] != -yyn {
			yystate = yyAct[yyg]
		}
	}
	// dummy call; replaced with literal code
	switch yynt {

	case 1:
		yyDollar = yyS[yypt-1 : yypt+1]
//line syntax.y:36
		{
			yylex.(*parser).line(yyDollar[1].line)
		}
	case 2:
		yyDollar = yyS[yypt-2 : yypt+1]
//line syntax.y:37
		{
			yylex.(*parser).line(yyDollar[2].line)
		}
	case 3:
		yyDollar = yyS[yypt-5 : yypt+1]
//line syntax.y:40
		{
			yyVAL.line = &ast.Line{Num: yyDollar[2].bits, Stmt: yyDollar[4].stmt, Goto0: yyDollar[5].bit2[0], Goto1: yyDollar[5].bit2[1]}
		}
	case 4:
		yyDollar = yyS[yypt-1 : yypt+1]
//line syntax.y:42
		{
			yyVAL.stmt = &ast.Read{}
		}
	case 5:
		yyDollar = yyS[yypt-2 : yypt+1]
//line syntax.y:43
		{
			yyVAL.stmt = &ast.Print{Val: yyDollar[2].bit}
		}
	case 6:
		yyDollar = yyS[yypt-3 : yypt+1]
//line syntax.y:45
		{
			if !ast.CanAssign(yyDollar[1].expr) {
				yylex.Error("cannot assign to " + yyDollar[1].expr.String())
			}
			yyVAL.stmt = &ast.Equals{Left: yyDollar[1].expr, Right: yyDollar[3].expr}
		}
	case 7:
		yyDollar = yyS[yypt-3 : yypt+1]
//line syntax.y:53
		{
			if !ast.CanVal(yyDollar[1].expr) {
				yylex.Error("cannot take value of " + yyDollar[1].expr.String())
			}
			if !ast.CanVal(yyDollar[3].expr) {
				yylex.Error("cannot take value of " + yyDollar[3].expr.String())
			}
			yyVAL.expr = &ast.Nand{Left: yyDollar[1].expr, Right: yyDollar[3].expr}
		}
	case 8:
		yyDollar = yyS[yypt-1 : yypt+1]
//line syntax.y:62
		{
			yyVAL.expr = yyDollar[1].expr
		}
	case 9:
		yyDollar = yyS[yypt-5 : yypt+1]
//line syntax.y:64
		{
			yyVAL.expr = yyDollar[3].expr
		}
	case 10:
		yyDollar = yyS[yypt-4 : yypt+1]
//line syntax.y:66
		{
			if !ast.CanDeref(yyDollar[4].expr) {
				yylex.Error("cannot dereference " + yyDollar[4].expr.String())
			}
			yyVAL.expr = &ast.ValueAt{Ptr: yyDollar[4].expr}
		}
	case 11:
		yyDollar = yyS[yypt-4 : yypt+1]
//line syntax.y:73
		{
			if !ast.CanDeref(yyDollar[4].expr) {
				yylex.Error("cannot dereference " + yyDollar[4].expr.String())
			}
			yyVAL.expr = &ast.ValueBeyond{Ptr: yyDollar[4].expr}
		}
	case 12:
		yyDollar = yyS[yypt-3 : yypt+1]
//line syntax.y:80
		{
			if !ast.CanAddr(yyDollar[3].expr) {
				yylex.Error("cannot take address of " + yyDollar[3].expr.String())
			}
			yyVAL.expr = &ast.AddressOf{Val: yyDollar[3].expr}
		}
	case 13:
		yyDollar = yyS[yypt-2 : yypt+1]
//line syntax.y:87
		{
			yyVAL.expr = &ast.JumpRegister{}
		}
	case 14:
		yyDollar = yyS[yypt-2 : yypt+1]
//line syntax.y:88
		{
			yyVAL.expr = &ast.Variable{Num: yyDollar[2].bits}
		}
	case 15:
		yyDollar = yyS[yypt-1 : yypt+1]
//line syntax.y:89
		{
			yyVAL.expr = &ast.Constant{Val: yyDollar[1].bit}
		}
	case 16:
		yyDollar = yyS[yypt-0 : yypt+1]
//line syntax.y:92
		{
			yyVAL.bit2 = [2]ast.Bits{nil, nil}
		}
	case 17:
		yyDollar = yyS[yypt-2 : yypt+1]
//line syntax.y:94
		{
			yyVAL.bit2 = [2]ast.Bits{yyDollar[2].bits, yyDollar[2].bits}
		}
	case 18:
		yyDollar = yyS[yypt-7 : yypt+1]
//line syntax.y:96
		{
			yyVAL.bit2 = [2]ast.Bits{yyDollar[2].bits, nil}
		}
	case 19:
		yyDollar = yyS[yypt-7 : yypt+1]
//line syntax.y:98
		{
			yyVAL.bit2 = [2]ast.Bits{nil, yyDollar[2].bits}
		}
	case 20:
		yyDollar = yyS[yypt-14 : yypt+1]
//line syntax.y:100
		{
			yyVAL.bit2 = [2]ast.Bits{yyDollar[2].bits, yyDollar[9].bits}
		}
	case 21:
		yyDollar = yyS[yypt-14 : yypt+1]
//line syntax.y:102
		{
			yyVAL.bit2 = [2]ast.Bits{yyDollar[9].bits, yyDollar[2].bits}
		}
	case 22:
		yyDollar = yyS[yypt-1 : yypt+1]
//line syntax.y:104
		{
			yyVAL.bits = ast.Bits{yyDollar[1].bit}
		}
	case 23:
		yyDollar = yyS[yypt-2 : yypt+1]
//line syntax.y:105
		{
			yyVAL.bits = append(yyDollar[1].bits, yyDollar[2].bit)
		}
	case 24:
		yyDollar = yyS[yypt-1 : yypt+1]
//line syntax.y:107
		{
			yyVAL.bit = ast.Zero
		}
	case 25:
		yyDollar = yyS[yypt-1 : yypt+1]
//line syntax.y:108
		{
			yyVAL.bit = ast.One
		}
	}
	goto yystack /* stack new state and value */
}
